package io.github.bysenom.relicwrought.item.generation;

public enum GenerationErrorCode {
    NONE,
    MISSING_ITEM_BASE,
    NO_ELIGIBLE_ITEM_BASE,
    INVALID_ITEM_LEVEL,
    INVALID_RARITY,
    RARITY_NOT_UNLOCKED,
    INVALID_QUALITY,
    NO_VALID_SLOT_DISTRIBUTION,
    AFFIX_GENERATION_FAILED,
    BASE_STAT_SCALING_FAILED,
    PERSISTENCE_WRITE_FAILED,
    INVALID_GENERATED_ITEM,
    UNSUPPORTED_ITEM_CATEGORY
}
